[package]
name = "papersmith"
description = "AI-Powered PDF Renamer in Rust."
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
colog = "1.3.0"
dotenvy = "0.15.7"
log = "0.4.22"
tokio = { version = "1.42.0", features = ["full"] }
image = "0.25.5"
pdf2image = "0.1.2"
async-openai = "0.26.0"
serde_json = "1.0.134"
base64 = "0.22.1"
repair_json = "0.1.0"
serde = "1.0.216"
glob = "0.3.1"
regex = "1.11.1"

[profile.release]
strip = true
lto = true
codegen-units = 1
